"""001 v3 + a short entrance bridge: regenerate only source frames 46-80 so no frame shows the source Itadori.

User (2026-10-01): “001的镜头也处理一下。真正有问题的也就是1秒左右虎杖的残影”. v3 switched from source to generation at frame 63 with a
crossfade over 63-68, but the source boy's hood enters at the left edge around frames 58-60 - those frames showed him. Instead of
regenerating 192 frames (away mode only), generate the bridge 46-80 (35 frames, fits present mode) with v3's own generated frame at
source frame 80 as the last-frame keyframe (h3 keyframe anchor method, as Fate's armor shot “ends on <Picture 2>”), then splice:
source 0-45, crossfade 46-51 into the bridge (the street is still empty), bridge, crossfade 77-80 into v3's generation, v3 81-237.
"""
import json
import pathlib
import subprocess
import sys

import numpy as np
from PIL import Image

import render_shot as runner
import render_001_v3  # noqa: F401  (v3 reference, label and prompt on render_001)
import render_001 as v3
from common import PROD, p
from gpu import wait_cool

UID, REV = '001', 'deepseek_bridge_h3_v1'
B0, B1 = 46, 81                     # source frames regenerated by the bridge
FADE_IN, FADE_OUT = (46, 52), (77, 81)  # source -> bridge, bridge -> v3 generation
V3 = PROD / 'shots/001/deepseek_official_redblack_h3_v3'
V3_JOINED = PROD / 'shots/001/deepseek_official_redblack_h3_v3_joined'
KF = PROD / 'character_designs/refs/kf_001_v3gen_f80.png'
SEED = 2610010046
LABEL = '001 v3＋入场桥接（只重做第46–80帧，去掉虎杖残影）'


def frames(path):
    raw = subprocess.run([str(p.FFMPEG), '-v', 'error', '-i', str(path), '-vsync', '0', '-f', 'rawvideo', '-pix_fmt', 'rgb24', '-'],
                         capture_output=True, check=True).stdout
    return np.frombuffer(raw, np.uint8).reshape(-1, 576, 1024, 3)


def prompt(g):
    ts = f'00:{(g - 1) / 24:06.3f}'
    s = v3.PROMPT
    s = s.replace('<Video 1> is the source video for the target video edit.',
                  f'<Picture 2> is the last frame of [Shot 1] at {ts}: <Subject 1> walking into the red-and-black street from the left, '
                  'exactly as the target video must look at that moment.\n<Video 1> is the source video for the target video edit.')
    s = s.replace('[video editing + reference generation] The target video', '[video editing + reference generation + keyframe completion] The target video')
    s = s.replace('the timing and the red-and-black two-tone look.', f'the timing and the red-and-black two-tone look, and [Shot 1] ends on <Picture 2>.')
    s = s.replace('<Video 1> (source video editing):', f'<Picture 2> ([Shot 1] last frame at {ts}): fully_preserved - the final frame matches her '
                  'position, pose, hair, dress, the street and the composition.\n<Video 1> (source video editing):')
    s = s.replace('over this 7.292-second model sequence.', f'over this {g / 24:.3f}-second model sequence.')
    old = ('[Shot 1] 2D-animated, a red-and-black two-tone city street seen from low, a black sun with a glowing red ring in the sky; <Subject 1> walks in '
           'from the left very close to the camera; the camera turns around her head as she walks; at the end, seen from behind and below, the black sun '
           'behind her head forms a red halo.')
    assert old in s
    s = s.replace(old, '[Shot 1] 2D-animated, a red-and-black two-tone city street seen from low, a black sun with a glowing red ring in the sky; '
                       'at first the street is empty as the camera glides forward, then <Subject 1> walks in from the left edge very close to the '
                       'camera, and the shot ends on <Picture 2>.')
    for gone in ('7.292-second', 'forms a red halo.'):
        assert gone not in s.split('detailed_description:')[1].split('overall_soundscape:')[0] or gone == 'forms a red halo.', gone
    return s


def compose(bridge_dir):
    src = frames(V3_JOINED / 'source_exact_with_audio.mp4')
    old = frames(V3_JOINED / 'review_with_audio.mp4')
    bridge = frames(bridge_dir / 'native_fullframe.mp4')
    assert len(src) == len(old) == 238 and len(bridge) == B1 - B0, (len(src), len(old), len(bridge))
    out = []
    for i in range(238):
        if i < FADE_IN[0]:
            out.append(src[i])
        elif i < FADE_IN[1]:
            w = (i - FADE_IN[0] + 1) / (FADE_IN[1] - FADE_IN[0] + 1)
            out.append(np.clip(src[i] * (1 - w) + bridge[i - B0] * w, 0, 255).astype(np.uint8))
        elif i < FADE_OUT[0]:
            out.append(bridge[i - B0])
        elif i < FADE_OUT[1]:
            w = (i - FADE_OUT[0] + 1) / (FADE_OUT[1] - FADE_OUT[0] + 1)
            out.append(np.clip(bridge[i - B0] * (1 - w) + old[i] * w, 0, 255).astype(np.uint8))
        else:
            out.append(old[i])
    dest = PROD / 'shots' / UID / f'{REV}_joined'
    dest.mkdir(parents=True, exist_ok=True)
    full = V3_JOINED / 'source_exact_with_audio.mp4'
    silent = dest / 'native_fullframe.mp4'
    proc = subprocess.run([str(p.FFMPEG), '-v', 'error', '-y', '-f', 'rawvideo', '-pix_fmt', 'rgb24', '-s', '1024x576', '-r', '24000/1001',
                           '-i', '-', '-frames:v', '238', '-c:v', 'libx264', '-crf', '12', '-pix_fmt', 'yuv420p', str(silent)],
                          input=np.stack(out).tobytes(), capture_output=True)
    assert proc.returncode == 0, proc.stderr
    clip = dest / 'review_with_audio.mp4'
    p.run([p.FFMPEG, '-v', 'error', '-y', '-i', silent, '-i', full, '-map', '0:v:0', '-map', '1:a:0', '-c', 'copy', '-movflags', '+faststart', clip])
    runner.configure(dest)
    check = runner.batch.validate_output(clip, 238, True)
    parts = [dict(label=f'H3 入场桥接：第 {B0}–{B1 - 1} 帧（末帧锚定 v3 第 80 帧）', workflow=str(bridge_dir / 'workflow.json'),
                  workflow_sha256=p.sha(bridge_dir / 'workflow.json')),
             dict(label='H3 v3：第 63–237 帧（本版只用第 77 帧以后）', workflow=str(V3 / 'workflow.json'), workflow_sha256=p.sha(V3 / 'workflow.json'))]
    record = dest / 'multistage.json'
    p.write_json(record, dict(kind='h3_multistage', parts=parts, note=(
        f'第 0–{B0 - 1} 帧原片；第 {FADE_IN[0]}–{FADE_IN[1] - 1} 帧从原片淡入桥接（此时人物还没进画）；第 {FADE_IN[1]}–{FADE_OUT[0] - 1} 帧桥接；'
        f'第 {FADE_OUT[0]}–{FADE_OUT[1] - 1} 帧从桥接淡入 v3 生成段；之后为 v3。原片原音。')))
    p.write_json(dest / 'validation.json', dict(video=str(clip), sha256=p.sha(clip), validation=check, visual_review='pending_user'))
    entry = next(s for s in runner.batch.read(runner.REVIEW / 'manifest.json')['shots'] if s['id'] == UID)
    if not any(v['video_sha256'] == p.sha(clip) for v in entry['versions']):
        runner.review.register(UID, str(clip), record, LABEL)
    return clip


def main():
    import msvcrt
    job = PROD / 'shots' / UID / REV
    job.mkdir(parents=True, exist_ok=True)
    if not KF.exists():
        gen = frames(V3 / 'native_fullframe.mp4')
        Image.fromarray(gen[80 - v3.CUT]).save(KF)  # v3's generation starts at source frame 63
    g = p.snap_frames(B1 - B0)
    text = prompt(g)
    if (job / 'prompt.txt').exists():
        assert (job / 'prompt.txt').read_text(encoding='utf-8') == text
    else:
        (job / 'prompt.txt').write_text(text, encoding='utf-8')
    runner.REFERENCES[UID] = [v3.REF, KF]
    runner.SEEDS[UID], runner.LABELS[UID] = SEED, LABEL
    runner.SHOT_OVERRIDES[UID] = dict(id=UID, start=B0, end=B1, frames=B1 - B0)
    runner.register = lambda job, sid: None  # registered only as the joined 238-frame unit
    with (PROD / 'batch.lock').open('a+b') as lock:
        lock.seek(0)
        msvcrt.locking(lock.fileno(), msvcrt.LK_NBLCK, 1)
        runner.prepare(UID, REV)
        p.write_json(job / 'authorization.json', dict(request='用户：001的镜头也处理一下。真正有问题的也就是1秒左右虎杖的残影（2026-10-01）',
                                                      references=[str(v3.REF), str(KF)], interval=[B0, B1], visual_review='pending_user'))
        if '--prepare-only' in sys.argv:
            print('PREPARED', job, g, 'model frames', flush=True)
            return
        if not (job / 'validation.json').exists():
            wait_cool()
        sys.argv = [__file__, '--shot', UID, '--revision', REV]
        runner.main()
    print('DONE', compose(job), flush=True)


if __name__ == '__main__':
    main()
